<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Hexlet Javalin Example</title>
</head>
<body>
<p>
    <a href="/users">Users</a>
</p>
<p>
    <a href="/users/build">Add User</a>
</p>
<p>
    <a href="/courses">Courses</a>
</p>
<p>
    <a href="/courses/build">Add Course</a>
</p>
</body>
</html>